In [1]:
2 ** 1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [3]:
np.int64(2) ** 1000

0

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
type(arr[1])

numpy.int64

In [6]:
arr.dtype

dtype('int64')

In [8]:
v = np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
v.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
mat = np.arange(12).reshape((4,3))
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
mat.shape

(4, 3)